oldSolution/lab484/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

oldSolution/lab484/Pages/Index.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace lab484.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnGet(string logout)
        {
            if (logout == "true")
            {
                HttpContext.Session.Clear();
                ViewData["LoginMessage"] = "Successfully Logged Out!";
            }

            string loginError = HttpContext.Session.GetString("LoginError");
            if (!string.IsNullOrEmpty(loginError))
            {
                ViewData["LoginMessage"] = loginError;
                HttpContext.Session.Remove("LoginError"); // Clear after displaying
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            string loginQuery = "SELECT COUNT(*) FROM users WHERE Username = @Username AND Password = @Password";
            string findUserID = "SELECT UserID FROM users WHERE Username = @Username AND Password = @Password";

            // check if login credentials are valid
            if (DBClass.HashedLogin(Username, Password))
            {
                DBClass.DBConnection.Close();
                HttpContext.Session.SetInt32("loggedIn", 1);
                HttpContext.Session.SetString("username", Username);

                // retrieve userIDs
                int userID = DBClass.HashedUserID(Username);
                HttpContext.Session.SetInt32("userID", userID);
                DBClass.DBConnection.Close();

                // check user permissions
                int adminStatus = DBClass.adminCheck(userID);
                DBClass.DBConnection.Close();
                if (adminStatus == 1)
                {
                    HttpContext.Session.SetInt32("adminStatus", 1);
                    return RedirectToPage("/Admin/AdminLanding");
                }
                else
                {
                    int facultyStatus = DBClass.facultyCheck(userID);
                    if (facultyStatus == 1)
                    {
                        DBClass.DBConnection.Close();
                        HttpContext.Session.SetInt32("facultyStatus", 1);
                        return RedirectToPage("/Faculty/FacultyLanding");
                    }
                    else
                    {
                        DBClass.DBConnection.Close();
                        return RedirectToPage("/NoPermissions");
                    }
                }
            }
            else
            {
                ViewData["LoginMessage"] = "Username and/or Password Incorrect";
                return Page();
            }
        }


        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return Page();
        }
    }
}

oldSolution/lab484/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages
{
    public class LogoutModel : PageModel
    {
        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

oldSolution/lab484/Pages/Messages.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Diagnostics;

namespace lab484.Pages
{
    public class MessagesModel : PageModel
    {
        [BindProperty]
        [Required(ErrorMessage = "Must select a user to send message to.")]
        public int SelectedUsername { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Must include a subject title.")]
        public string MessageSubject { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Must include message content.")]
        public string MessageContent { get; set; }
        public List<SelectListItem> Usernames { get; set; } = new List<SelectListItem>();

        public User activeUser { get; set; }

        public string usr { get; set; } // Declare usr as a property of the class

        public required List<Message> receivedList { get; set; } = new List<Message>();
        public string SuccessMessage { get; set; }

        public IActionResult OnGet()
        {
            // Retrieve the username from the session here
            usr = HttpContext.Session.GetString("username");

            if (usr == null)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("Index"); // Redirect to login page
            }

            Usernames = new List<SelectListItem>();

            // Execute the userReader method from DBClass to load the usernames 
            using (SqlDataReader reader = DBClass.UserReader())
            {
                while (reader.Read())
                {
                    Usernames.Add(new SelectListItem
                    {
                        Value = reader["UserID"].ToString(),
                        Text = reader["Username"].ToString()
                    });
                }
                reader.Close();
                DBClass.DBConnection.Close();
            }

            // Initialize activeUser to avoid NullReferenceException
            activeUser = new User();
            Trace.WriteLine("Initialized activeUser object");

            using (SqlDataReader singleUserReader = DBClass.SingleUserReader(usr))
            {
                if (singleUserReader != null && singleUserReader.HasRows)
                {
                    while (singleUserReader.Read())
                    {
                        Trace.WriteLine("Reading singleUserReader data");
                        activeUser.UserID = int.Parse(singleUserReader["UserID"].ToString());
                        activeUser.UserName = singleUserReader["Username"].ToString();
                        activeUser.FirstName = singleUserReader["FirstName"].ToString();
                        activeUser.LastName = singleUserReader["Lastname"].ToString();
                        activeUser.Email = singleUserReader["Email"].ToString();
                        Trace.WriteLine($"Active user details: {activeUser.UserID} {activeUser.UserName}, {activeUser.Email}");
                    }
                    singleUserReader.Close();

                    HttpContext.Session.SetInt32("ActiveUserID", activeUser.UserID);
                }
            }

            DBClass.DBConnection.Close();

            // Ensure receivedList is not null
            receivedList = new List<Message>();

            if (activeUser != null)
            {
                // Retrieve received messages
                LoadReceivedMessages(activeUser.UserID);
            }

            return Page();
        }

        public IActionResult OnPost()
        {

            int? activeUserID = HttpContext.Session.GetInt32("ActiveUserID");

            if (activeUserID.HasValue)
            {
                LoadReceivedMessages(activeUserID.Value);
            }

            using (SqlDataReader reader = DBClass.UserReader())
            {
                while (reader.Read())
                {
                    Usernames.Add(new SelectListItem
                    {
                        Value = reader["UserID"].ToString(),
                        Text = reader["Username"].ToString()
                    });
                }
                reader.Close();
                DBClass.DBConnection.Close();
            }

            if (ModelState.IsValid)
            {
                Trace.WriteLine("Its not null!");
                DBMessage.InsertUserMessage(activeUserID, SelectedUsername, MessageSubject, MessageContent);
                SuccessMessage = "Message sent successfully!";

                MessageContent = string.Empty;
                MessageSubject = string.Empty;
                SelectedUsername = 0; // Reset dropdown selection

                ModelState.Clear();

                return Page();
            }
            else
            {
                using (SqlDataReader reader = DBClass.UserReader())
                {
                    while (reader.Read())
                    {
                        Usernames.Add(new SelectListItem
                        {
                            Value = reader["UserID"].ToString(),
                            Text = reader["Username"].ToString()
                        });
                    }
                    reader.Close();
                    DBClass.DBConnection.Close();
                }

                return Page();
            }
        }

        // method specifically for loading the messages 
        private void LoadReceivedMessages(int userId)
        {
            receivedList = new List<Message>();

            using (SqlDataReader receivedReader = DBMessage.singleRecipientReader(userId))
            {
                while (receivedReader.Read())
                {
                    receivedList.Add(new Message
                    {
                        SenderID = int.Parse(receivedReader["SenderID"].ToString()),
                        SenderUsername = receivedReader["SenderUsername"].ToString(),
                        RecipientID = int.Parse(receivedReader["RecipientID"].ToString()),
                        RecipientUsername = receivedReader["RecipientUsername"].ToString(),
                        SubjectTitle = receivedReader["SubjectTitle"].ToString(),
                        Contents = receivedReader["Contents"].ToString(),
                        MessageID = int.Parse(receivedReader["MessageID"].ToString()),
                        SentTime = DateTime.Parse(receivedReader["SentTime"].ToString())
                    });
                }
                receivedReader.Close();
            }
            DBMessage.DBConnection.Close();
        }

    }
}

oldSolution/lab484/Pages/NoPermissions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages
{
    public class NoPermissionsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

oldSolution/lab484/Pages/Search.cshtml.cs
using lab484.Pages.Data_Classes;
using lab484.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Diagnostics;

namespace lab484.Pages
{
    public class SearchModel : PageModel
    {
        [BindProperty] 
        public string searchWord { get; set; }

        public required List<SearchResult> searchList { get; set; } = new List<SearchResult>();

        public IActionResult OnGet()
        {
            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            SqlDataReader searchReader = DBClass.SearchFunction(searchWord);
            while (searchReader.Read())
            {
                searchList.Add(new SearchResult
                {
                    TableName = searchReader["TableName"].ToString(),
                    ColumnName = searchReader["ColumnName"].ToString(),
                    foundValue = searchReader["FoundValue"].ToString()
                });
            }
            DBClass.DBConnection.Close();
            Trace.WriteLine(searchList.Count);
            return Page();
        }
    }
}

oldSolution/lab484/Pages/SendMessages.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages
{
    public class SendMessagesModel : PageModel
    {
        // not done yet 
        public int UserID { get; set; }
        public IActionResult OnGet(int userID)
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("Index"); // Redirect to login page
            }

            this.UserID = userID;

            return Page();
        }
    }
}

oldSolution/lab484/Pages/addUser.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace lab484.Pages
{
    public class addUserModel : PageModel
    {
        [BindProperty]
        public User NewUser { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPostAdd()
        {
            if (ModelState.IsValid)
            {
                DBClass.InsertUser(NewUser);

                return RedirectToPage("Index");
            }

            return Page();

        }

        public IActionResult OnPostClear()
        {
            ModelState.Clear();
            NewUser = new User
            {
                UserID = NewUser.UserID, // Keep the UserID the same
                UserName = string.Empty,
                Password = string.Empty,
                FirstName = string.Empty,
                LastName = string.Empty,
                Email = string.Empty,
                Phone = string.Empty,
                HomeAddress = string.Empty
            };

            // Return the page with the cleared model
            return Page();
        }

        public IActionResult OnPostPopulate()
        {
            ModelState.Clear();
            NewUser = new User
            {
                UserID = NewUser.UserID, // Keep the UserID the same
                UserName = "ILove484SoMuch",
                Password = "12345",
                FirstName = "sam",
                LastName = "ogden",
                Email = "thesamogden@gmail.com",
                Phone = "12345567",
                HomeAddress = "11 NUN YA BUSINESS"
            };

            return Page();
        }
    }


}

oldSolution/lab484/Pages/Index.cshtml
@page
@model lab484.Pages.IndexModel
@{

}

<br />
<br />
<h2 class="text-center">Grant Management System</h2>
<p class="text-center">Created by: Nick Clement, Sam Ogden, Josh White, and Nadeem Hudson</p>
<br />

@{
    if (ViewData["LoginMessage"] != null)
    {
        <div class="text-center">
            <p class="text-danger fw-bold">@ViewData["LoginMessage"]</p>
        </div>
    }
}

@{
    if (HttpContext.Session.GetString("username") != null)
    {
        <div class="text-center">
        <p>@HttpContext.Session.GetString("username") logged in</p>

        
        <form asp-page="Index" asp-page-handler="LogoutHandler">
            <input type="submit" class="btn btn-danger" value="Logout">
        </form>
        </div>
    }
    else
    {
        <form method="post" asp-page="Index">
            <div class="form-floating mb-3">
                <input asp-for="Username" class="form-control" id="floatingUsername" placeholder="Username" />
                <label for="floatingUsername">Username</label>
            </div>
            <div class="form-floating">
                <input asp-for="Password" class="form-control" id="floatingPassword" type="password" placeholder="Password" />
                <label for="floatingPassword">Password</label>
            </div>

            <a class="btn btn-link" asp-page="addUser">Add New User</a>

            <div class="text-center">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </form>
    }
}

oldSolution/lab484/Pages/Logout.cshtml
@page
@model lab484.Pages.LogoutModel
@{
}

oldSolution/lab484/Pages/Messages.cshtml
@page 
@model lab484.Pages.MessagesModel

@{
}
<meta charset="utf-8" />
<br />
<h2 class="text-center">Received Messages</h2>
<br />
<table class="table">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Sender</th>
            <th>Contents</th>
            <th>Received Time</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.receivedList != null && Model.receivedList.Count > 0)
        {
            @foreach (var message in Model.receivedList)
            {
                <tr>
                    <td>@message.SubjectTitle</td>
                    <td>@message.SenderUsername</td>
                    <td>@message.Contents</td>
                    <td>@message.SentTime</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="4">No messages found.</td>
            </tr>
        }
</table>
<br />
<br />
<h2 class="text-center">Send Message</h2>
<br />
<form method="post">
    @if (Model.SuccessMessage != null)
    {
        <div class="alert alert-success">
            @Model.SuccessMessage
        </div>
    }
<div class="form-group row justify-content-center">
    <select class="form-control username-select" asp-for="SelectedUsername">
        <option value="" disabled selected>Select Recipient</option>
        @foreach (var item in Model.Usernames)
        {
            <option value="@item.Value">@item.Text</option>
        }
    </select>
    <span asp-validation-for="@Model.SelectedUsername" class="text-danger"></span>
</div>
<br />
<div class="form-group row justify-content-center">
    <input type="text" class="form-control subject-input" asp-for="MessageSubject"  placeholder="Enter Subject">
    <span asp-validation-for="@Model.MessageSubject" class="text-danger"></span>
</div>
<br />
<div class="form-group row justify-content-center">
    <textarea class="form-control message-textarea" rows="5" asp-for="MessageContent"  placeholder="Enter Message"></textarea>
    <span asp-validation-for="@Model.MessageContent" class="text-danger"></span>
</div>
<br />
<div class="sendbutton form-group row justify-content-center">
    <button type="submit" class="btn btn-primary">Send</button>
</div>
</form>

oldSolution/lab484/Pages/NoPermissions.cshtml
@page
@model lab484.Pages.NoPermissionsModel
@{
}
<h2>Hi there! Looks like you are not allowed to view any pages in the system :(</h2>
<h4>Please enjoy this dancing cat:</h4>
<img src="https://media.tenor.com/5BYK-WS0__gAAAAM/cool-fun.gif" />

oldSolution/lab484/Pages/Search.cshtml
@page
@model lab484.Pages.SearchModel
@{
}
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<br />
<h2 class="text-center">Search System</h2>
<br />

<form method="post" class="mb-3">
    <div class="form-group">
        <input type="text" placeholder="Search Term..." name="searchWord" class="form-control" asp-for="searchWord" />
    </div>
    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

<br />

@if (Model.searchList != null && Model.searchList.Count > 0)
{
    <h3 class="text-center">@Model.searchList.Count Results for "<span class="text-primary">@Model.searchWord</span>":</h3>
    <br />
    <table class="table table-bordered table-hover table-responsive">
        <thead class="thead-dark">
            <tr>
                <th>Table Name</th>
                <th>Column Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model.searchList)
            {
                <tr>
                    <td>@result.TableName</td>
                    <td>@result.ColumnName</td>
                    <td>@result.foundValue</td>
                </tr>
            }
        </tbody>
    </table>
}
else if (!string.IsNullOrEmpty(Model.searchWord))
{
    <div class="alert alert-warning text-center">
        No results found for "<span class="text-danger">@Model.searchWord</span>".
    </div>
}

oldSolution/lab484/Pages/SendMessages.cshtml
@page
@model lab484.Pages.SendMessagesModel
@{
}
<h2>Send Message from @Model.UserID</h2>
<p>still in progress :3</P>

oldSolution/lab484/Pages/ViewMessages.cshtml
@page
@model lab484.Pages.ViewMessagesModel
@{
}

<h1>Sent Messages</h1>
<table class="table">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Recipient</th>
            <th>Contents</th>
            <th>Sent Time</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model.sentList)
        {
            <tr>
                <td>@message.SubjectTitle</td>
                <td>@message.RecipientUsername</td>
                <td>@message.Contents</td>
                <td>@message.SentTime</td>
            </tr>
        }
    </tbody>
</table>

<h1>Received Messages</h1>
<table class="table">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Sender</th>
            <th>Contents</th>
            <th>Received Time</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var message in Model.receivedList)
        {
            <tr>
                <td>@message.SubjectTitle</td>
                <td>@message.SenderUsername</td>
                <td>@message.Contents</td>
                <td>@message.SentTime</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-page="SendMessages" asp-route-userID="@Model.userID" class="btn btn-primary">Send Message</a>
</div>

oldSolution/lab484/Pages/addUser.cshtml
@page
@model lab484.Pages.addUserModel
@{
}
<br />
<h2 class="text-center">Add New User</h2>
<br />
<form method="post" class="form-horizontal">
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.UserName" placeholder="Username" />
        <label asp-for="NewUser.UserName">Username</label>
        <span asp-validation-for="NewUser.UserName" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.Password" placeholder="Password" />
        <label asp-for="NewUser.Password">Password</label>
        <span asp-validation-for="NewUser.Password" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.FirstName" placeholder="First Name" />
        <label asp-for="NewUser.FirstName">First Name</label>
        <span asp-validation-for="NewUser.FirstName" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.LastName" placeholder="Last Name" />
        <label asp-for="NewUser.LastName">Last Name</label>
        <span asp-validation-for="NewUser.LastName" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="email" class="form-control" asp-for="NewUser.Email" placeholder="Email" />
        <label asp-for="NewUser.Email">Email</label>
        <span asp-validation-for="NewUser.Email" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.Phone" placeholder="Phone" />
        <label asp-for="NewUser.Phone">Phone</label>
        <span asp-validation-for="NewUser.Phone" class="text-danger"></span>
    </div>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" asp-for="NewUser.HomeAddress" placeholder="Home Address" />
        <label asp-for="NewUser.HomeAddress">Home Address</label>
        <span asp-validation-for="NewUser.HomeAddress" class="text-danger"></span>
    </div>
    <div class="text-center">
        <input type="submit" class="btn btn-primary" asp-page-handler="Add" value=" Add User" />
        <button type="submit" class="btn btn-warning" asp-page-handler="Clear">Clear</button>
        <a asp-page="/index" class="btn btn-secondary">Cancel</a>
    </div>
</form>
<br />
<div class="text-center">
    <form method="post">
        <button type="submit" class="btn btn-outline-primary" asp-page-handler="Populate">Populate</button>
    </form>
</div>