oldSolution/lab484/Pages/Admin/AdminLanding.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace lab484.Pages.Admin
{
    public class AdminLandingModel : PageModel
    {
        public required List<ProjectSimple> projectList { get; set; } = new List<ProjectSimple>();
        [BindProperty]
        public bool DisplayAll { get; set; }
        [BindProperty]
        public String TableButton { get; set; } = "Expand";
        public IActionResult OnGet()
        {
            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            SqlDataReader projectReader = DBProject.ProjectReader();
            while (projectReader.Read())
            {
                // populate the projectList 
                projectList.Add(new ProjectSimple
                {
                    ProjectID = Int32.Parse(projectReader["ProjectID"].ToString()),
                    ProjectName = projectReader["ProjectName"].ToString(),
                    DueDate = DateTime.Parse(projectReader["DueDate"].ToString()),
                    Amount = 0f
                });
                // if the amount isnt a value, try converting it to a string then parsing a float from it 
                if (projectReader["Amount"] != DBNull.Value)
                {
                    if (projectReader["Amount"].ToString() != "")
                    {
                        projectList.Last().Amount = float.Parse(projectReader["Amount"].ToString());
                    }
                    else
                    {
                        projectList.Last().Amount = 0f;
                    }
                }
                else
                {
                    projectList.Last().Amount = 0f;
                }

            }

            // Close your connection in DBClass
            DBProject.DBConnection.Close();
            return Page();
        }

        public IActionResult OnPostToggleTable()
        {

            // method for the collapse / expand button 
            // stores the choice of the user in session state 
            bool DisplayAll = (HttpContext.Session.GetInt32("DisplayAll") == 1);

            // if true, set the button to expand 
            if (DisplayAll)
            {
                TableButton = "Expand";
                HttpContext.Session.SetInt32("DisplayAll", 0);
            }
            // if false set the button title to collapse 
            else
            {
                TableButton = "Collapse";
                HttpContext.Session.SetInt32("DisplayAll", 1);
            }

            // same validation from the top of page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            // loads projects 
            SqlDataReader projectReader = DBProject.ProjectReader();
            while (projectReader.Read())
            {
                // populate the projectList 
                projectList.Add(new ProjectSimple
                {
                    ProjectID = Int32.Parse(projectReader["ProjectID"].ToString()),
                    ProjectName = projectReader["ProjectName"].ToString(),
                    DueDate = DateTime.Parse(projectReader["DueDate"].ToString()),
                    Amount = 0f
                });
                // if the amount isnt a value, try converting it to a string then parsing a float from it 
                if (projectReader["Amount"] != DBNull.Value)
                {
                    if (projectReader["Amount"].ToString() != "")
                    {
                        projectList.Last().Amount = float.Parse(projectReader["Amount"].ToString());
                    }
                    else
                    {
                        projectList.Last().Amount = 0f;
                    }
                }
                else
                {
                    projectList.Last().Amount = 0f;
                }
            }
            DBProject.DBConnection.Close();
            return Page();
        }
    }
}

oldSolution/lab484/Pages/Faculty/AddGrant.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Diagnostics;

namespace lab484.Pages.Faculty
{
    public class AddGrantModel : PageModel
    {
        [BindProperty]
        public GrantSimple newGrant { get; set; }
        public List<GrantSupplier> SupplierList { get; set; } = new List<GrantSupplier>();

        public List<ProjectSimple> ProjectList { get; set; } = new List<ProjectSimple>();

        public int? CurrentUserID { get; set; } = new int?();

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("facultyStatus") != 1 && HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
                // made a method at the bottom of the file so i dont have to copy and paste it a bunch of times 
            SupplierList = LoadSuppliers();
            ProjectList = LoadProjects();

            return Page();
        }

        // executes when AddGrant is added, iinserts it into the db
        public IActionResult OnPostAddGrant()
        {
            SupplierList = LoadSuppliers();
            ProjectList = LoadProjects();

            // if everything is valid in the form, add to db with the supplierID selected 
            if (ModelState.IsValid)
            {
                // used AI for help with this, it associates the SupplierName in the list with the SupplierID
                GrantSupplier selectedSupplier = SupplierList.FirstOrDefault(s => s.SupplierName == newGrant.Supplier);
                ProjectSimple selectedProject = ProjectList.FirstOrDefault(p => p.ProjectName == newGrant.Project);
                int supplierID = selectedSupplier.SupplierID;
                int projectID = selectedProject.ProjectID;

                DBGrant.InsertGrant(newGrant, supplierID, projectID, Convert.ToInt32(HttpContext.Session.GetInt32("userID")));
                return RedirectToPage("FacultyLanding");
            }

            return Page();
        }

        // clears everything from form 
        public IActionResult OnPostClear()
        {
            ModelState.Clear();
            newGrant = new GrantSimple
            {
                GrantID = newGrant.GrantID, // Keep the GrantID the same
                Supplier = string.Empty,
                Project = string.Empty,
                Amount = 0,
                Category = string.Empty,
                Status = string.Empty,
                Description = string.Empty,
                SubmissionDate = DateTime.Now,
                AwardDate = DateTime.Now
            };

            // if i wasnt reloading the supplier list it would throw an error, this was an easy fix 
            OnGet(); // just to reload the supplier list

            // Return the page with the cleared model
            return Page();
        }


        // populate button 
        public IActionResult OnPostPopulate()
        {
            ModelState.Clear();
            newGrant = new GrantSimple
            {
                GrantName = "Hello My Name is Carmen Winstead",
                Supplier = "TechCorp",
                Project = "Project Alpha",
                Amount = 1000000,
                Category = "Federal",
                Status = "Pending",
                Description = "It's for the kids!",
                SubmissionDate = DateTime.Now,
                AwardDate = DateTime.Now
            };

            SupplierList = LoadSuppliers();// Reload supplier list
            ProjectList = LoadProjects();

            return Page();
        }


        // make a method so i dont have to copy and paste it each time 
        // loads all of the suppliers in the db into the supplierlist so it can be shown in the dropdown menu 
        private List<GrantSupplier> LoadSuppliers()
        {
            var suppliers = new List<GrantSupplier>();
            using (SqlDataReader reader = DBGrantSupplier.GrantSupplierReader())
            {
                while (reader.Read())
                {
                    suppliers.Add(new GrantSupplier
                    {
                        SupplierID = int.Parse(reader["SupplierID"].ToString()),
                        SupplierName = reader["SupplierName"].ToString(),
                        OrgType = reader["OrgType"].ToString(),
                        BusinessAddress = reader["BusinessAddress"].ToString()
                    });
                }
            }

            DBGrantSupplier.DBConnection.Close();

            return suppliers;
        }

        // make the same method for projects:
        private List<ProjectSimple> LoadProjects()
        {
            var projects = new List<ProjectSimple>();
            using (SqlDataReader reader = DBProject.ProjectReader())
            {
                while (reader.Read())
                {
                    projects.Add(new ProjectSimple
                    {
                        ProjectID = int.Parse(reader["ProjectID"].ToString()),
                        ProjectName = reader["ProjectName"].ToString()
                    });
                }
            }

            DBProject.DBConnection.Close();

            return projects;
        }
    }
}

oldSolution/lab484/Pages/Faculty/AddGrantNote.cshtml.cs
using System.Data.Common;
using System.Data.SqlClient;
using System.Diagnostics;
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages.Faculty
{
    public class AddGrantNoteModel : PageModel
    {
        [BindProperty]
        public GrantNote newGrantNote { get; set; } = new GrantNote();
        public GrantSimple grant {  get; set; } = new GrantSimple();
        public User user { get; set; } = new User();
        public int GrantID { get; set; }
        public IActionResult OnGet(int? GrantID)
        {
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("facultyStatus") != 1 && HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            if (GrantID == null)
            {
                GrantID = HttpContext.Session.GetInt32("grantID") ?? 0;
            }
            else
            {
                HttpContext.Session.SetInt32("grantID", Convert.ToInt32(GrantID));
            }


            this.GrantID = Convert.ToInt32(GrantID);

            SqlDataReader grantReader = DBGrant.SingleGrantReader(Convert.ToInt32(GrantID));
            while (grantReader.Read())
            {
                grant.GrantName = grantReader["GrantName"].ToString();
            }
            DBGrant.DBConnection.Close();

            user = DBClass.GetUserByID(Convert.ToInt32(HttpContext.Session.GetInt32("userID")));
            DBClass.DBConnection.Close();

            newGrantNote.GrantID = Convert.ToInt32(GrantID);
            newGrantNote.AuthorFirst = user.FirstName;
            newGrantNote.AuthorLast = user.LastName;
            newGrantNote.AuthorID = user.UserID;
            newGrantNote.TimeAdded = DateTime.Now;

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                DBGrant.InsertGrantNote(newGrantNote);
                return RedirectToPage("DetailedView", new { GrantID = newGrantNote.GrantID });
            }
            return Page();
        }

        public IActionResult OnPostClear()
        {
            ModelState.Clear();
            newGrantNote = new GrantNote();
            return RedirectToPage("AddGrantNote", new { GrantID = HttpContext.Session.GetInt32("grantID") });
        }

    }
}

oldSolution/lab484/Pages/Faculty/AssociateFac.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Diagnostics;

namespace lab484.Pages.Faculty
{
    public class AssociateFacModel : PageModel
    {
        [BindProperty]
        public int GrantID { get; set; }

        // make variable so we can access it w/o reading list 
        public string GrantName { get; set; }
        public required List<GrantStaff> StaffList { get; set; } = new List<GrantStaff>();
        public List<User> UserList { get; set; } = new List<User>();

        public IActionResult OnGet(int GrantID)
        {
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("facultyStatus") != 1 && HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            this.GrantID = GrantID;      // sets the GrantID



            // populates the ProjectName variable so it can be used
            // checks if there are any staff in list first
            SqlDataReader grantReader = DBGrant.SingleGrantReader(GrantID);
            if (grantReader.Read())
            {
                GrantName = grantReader["GrantName"].ToString();
            }
            DBGrant.DBConnection.Close();

            SqlDataReader facultyReader = DBFaculty.singleFacultyReader(GrantID);
            while (facultyReader.Read())
            {
                StaffList.Add(new GrantStaff
                {
                    UserID = Int32.Parse(facultyReader["UserID"].ToString()),
                    Username = facultyReader["Username"].ToString(),
                    FirstName = facultyReader["FirstName"].ToString(),
                    LastName = facultyReader["LastName"].ToString(),
                    Email = facultyReader["Email"].ToString(),
                    Phone = facultyReader["Phone"].ToString(),
                    HomeAddress = facultyReader["HomeAddress"].ToString(),
                    GrantName = facultyReader["GrantName"].ToString()
                });
            }
            DBFaculty.DBConnection.Close();

            // as long as there are faculty in the db for the method to read from the user will be added to the userList 
            using (SqlDataReader facReader = DBFaculty.facReader())
            {
                while (facReader.Read())
                {
                    UserList.Add(new User
                    {
                        UserID = Int32.Parse(facReader["UserID"].ToString()),
                        UserName = facReader["Username"].ToString()
                    });
                }
            }

            // Close your connection in DBClass
            DBFaculty.DBConnection.Close();
            return Page();
        }

        public IActionResult OnPostAddFaculty(int UserID)
        {
            // Retrieve the User object based on UserID
            User user = DBClass.GetUserByID(UserID);

            Trace.WriteLine($"ProjectID: {this.GrantID}");
            Trace.WriteLine($"UserID: {UserID}");

            if (user != null)
            {
                // why does ProjectID keep showing as 0 omg 
                DBGrant.InsertGrantStaff(user, this.GrantID);
            }


            // reloads the page 
            return RedirectToPage(new
            {
                GrantID = this.GrantID
            });

        }
    }
}

oldSolution/lab484/Pages/Faculty/AddGrant.cshtml
@page
@model lab484.Pages.Faculty.AddGrantModel
@{
}
<br />
<h2 class="text-center">Add New Grant</h2>
<br />
<form method="post" class="form-horizontal">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.GrantName">Grant Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="newGrant.GrantName" />
            <span asp-validation-for="newGrant.GrantName" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Supplier"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="newGrant.Supplier">
                <option value="" disabled selected>Select Supplier</option>
                @foreach (var supplier in Model.SupplierList)
                {
                    <option value="@supplier.SupplierName">@supplier.SupplierName</option>
                }
            </select>
            <span asp-validation-for="newGrant.Supplier" class="text-danger"></span>
        </div>
    </div>
    <br />

    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Project"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="newGrant.Project">
                <option value="" disabled selected>Select Project</option>
                @foreach (var project in Model.ProjectList)
                {
                    <option value="@project.ProjectName">@project.ProjectName</option>
                }
            </select>
            <span asp-validation-for="newGrant.Project" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Amount"></label>
        <div class="col-sm-10">
            <input type="number" class="form-control" asp-for="newGrant.Amount" />
            <span asp-validation-for="newGrant.Amount" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Category"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="newGrant.Category">
                <option value="" disabled selected>Select Category</option>
                <option value="Federal">Federal</option>
                <option value="State">State</option>
                <option value="University">University</option>
                <option value="Business">Business</option>
            </select>
            <span asp-validation-for="newGrant.Category" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Status"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="newGrant.Status">
                <option value="" disabled selected>Select Status</option>
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="Pending">Pending</option>
            </select>
            <span asp-validation-for="newGrant.Status" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.Description"></label>
        <div class="col-sm-10">
            <textarea class="form-control" asp-for="newGrant.Description" rows="5"></textarea>
            <span asp-validation-for="newGrant.Description" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.SubmissionDate">Submission Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" asp-for="newGrant.SubmissionDate" />
            <span asp-validation-for="newGrant.SubmissionDate" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrant.AwardDate">Award Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" asp-for="newGrant.AwardDate" />
            <span asp-validation-for="newGrant.AwardDate" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="text-center">
        <input type="submit" class="btn btn-success" asp-page-handler="AddGrant" value="Add Grant" />
        <button type="submit" class="btn btn-warning" asp-page-handler="Clear">Clear</button>
        <a asp-page="FacultyLanding" class="btn btn-secondary">Cancel</a>
        <br />
        <br />
    </div>
</form>

<div class="text-center">
    <form method="post">
        <button type="submit" class="btn btn-outline-primary" asp-page-handler="Populate">Populate</button>
    </form>
</div>

oldSolution/lab484/Pages/Faculty/AddGrantNote.cshtml
@page "{GrantID:int}"
@model lab484.Pages.Faculty.AddGrantNoteModel
@{
}


@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <p>@error.ErrorMessage</p>
        }
    </div>
}

<head>
    <meta charset="utf-8" />
    <title>Add Grant Note for @Model.grant.GrantName</title>
</head>
<br />
<h2 class="text-center">Add a Grant Note for @Model.grant.GrantName</h2>
<br />
<form method="post" class="form-horizontal">
    <input type="hidden" asp-for="newGrantNote.GrantID" value="@Model.newGrantNote.GrantID" />
    <input type="hidden" asp-for="newGrantNote.AuthorFirst" value="@Model.user.FirstName" />
    <input type="hidden" asp-for="newGrantNote.AuthorLast" value="@Model.user.LastName" />
    <input type="hidden" asp-for="newGrantNote.AuthorID" value="@Model.user.UserID" />
    <input type="hidden" asp-for="newGrantNote.TimeAdded" value="@Model.newGrantNote.TimeAdded" />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newGrantNote.Content">Content</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="newGrantNote.Content" required />
            <span class="text-danger" asp-validation-for="newGrantNote.Content"></span>
        </div>
    </div>
    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-outline-primary">Submit</button>
        <button type="submit" class="btn btn-outline-secondary" asp-page-handler="Clear" formnovalidate>Clear</button>
        <a asp-page="DetailedView" asp-route-grantID="@Model.GrantID" class="btn btn-secondary">Cancel</a>
        <br /><br />
    </div>
</form>

oldSolution/lab484/Pages/Faculty/AssociateFac.cshtml
@page "{GrantID:int}"
@model lab484.Pages.Faculty.AssociateFacModel

@{
}
<br />
<h2 class="text-center">Grant Staff for @Model.GrantName</h2>
<br />
<table class="table table-striped table-hover">
    <thead class="thead-light">
        <tr>
            <th class="table-header text-primary font-weight-bold text-decoration-none">Username</th>
            <th class="table-header text-primary font-weight-bold text-decoration-none">First Name</th>
            <th class="table-header text-primary font-weight-bold text-decoration-none">Last Name</th>
            <th class="table-header text-primary font-weight-bold text-decoration-none">Email</th>
            <th class="table-header text-primary font-weight-bold text-decoration-none">Phone</th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.StaffList.Any())
        {
            <tr>
                <td colspan="7" class="text-center">There are no faculty members working on this project.</td>
            </tr>
        }
        else
        {
            @foreach (var staff in Model.StaffList)
            {
                <tr>
                    <td>@staff.Username</td>
                    <td>@staff.FirstName</td>
                    <td>@staff.LastName</td>
                    <td>@staff.Email</td>
                    <td>@staff.Phone</td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="mt-3">
    <form method="post" asp-page-handler="AddFaculty">
        <input type="hidden" asp-for="GrantID" />
        <div class="form-group">
            <label for="UserID">Select Faculty Member to associate:</label>
            <select id="UserID" name="UserID" class="form-control">
                @foreach (var user in @Model.UserList)
                {
                    <option value="@user.UserID">@user.UserName</option>
                }
            </select>
        </div>
        <br />
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Associate Faculty</button>
        </div>
    </form>
</div>

<br />

<div class="text-center">
    <a class="btn btn-outline-primary" asp-page="DetailedView" asp-route-GrantID="@Model.GrantID">Back to Details</a>
</div>

oldSolution/lab484/Pages/Faculty/EditGrant.cshtml
@page
@model lab484.Pages.Faculty.EditGrantModel
@{
}

<div class="alert alert-danger">
    <ul>
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <li>@error.ErrorMessage</li>
        }
    </ul>
</div>
<br />
<h2 class="text-center">Editing Grant:</h2>
<br />
<form method="post" class="form-horizontal">
    <input type="hidden" asp-for="GrantToUpdate.GrantID" />

    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.GrantName">Grant Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="GrantToUpdate.GrantName" required />
            <span asp-validation-for="GrantToUpdate.GrantName" class="text-danger"></span>
        </div>
    </div>

    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Supplier"></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="GrantToUpdate.Supplier" required />
            <span asp-validation-for="GrantToUpdate.Supplier" class="text-danger"></span>
        </div>
    </div>
    
    @{
        if (Model.GrantToUpdate.Project != null)
        {
            <br />
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Project"></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" asp-for="GrantToUpdate.Project" />
                    <span asp-validation-for="GrantToUpdate.Project" class="text-danger"></span>
                </div>
            </div>
        }
    }

    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Amount"></label>
        <div class="col-sm-10">
            <input type="number" class="form-control" asp-for="GrantToUpdate.Amount" required />
            <span asp-validation-for="GrantToUpdate.Amount" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Category"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="GrantToUpdate.Category" required>
                <option value="" disabled selected>Select Category</option>
                <option value="Federal">Federal</option>
                <option value="State">State</option>
                <option value="University">University</option>
                <option value="Business">Business</option>
            </select>
            <span asp-validation-for="GrantToUpdate.Category" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Status"></label>
        <div class="col-sm-10">
            <select class="form-control" asp-for="GrantToUpdate.Status" required>
                <option value="" disabled selected>Select Status</option>
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="Pending">Pending</option>
            </select>
            <span asp-validation-for="GrantToUpdate.Status" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.Description"></label>
        <div class="col-sm-10">
            <textarea class="form-control" asp-for="GrantToUpdate.Description" rows="5" required></textarea>
            <span asp-validation-for="GrantToUpdate.Description" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.SubmissionDate">Submission Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" asp-for="GrantToUpdate.SubmissionDate" required />
            <span asp-validation-for="GrantToUpdate.SubmissionDate" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="GrantToUpdate.AwardDate">Award Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" asp-for="GrantToUpdate.AwardDate" required />
            <span asp-validation-for="GrantToUpdate.AwardDate" class="text-danger"></span>
        </div>
    </div>
    <br />
    <div class="text-center">
        <input type="submit" class="btn btn-success" value="Save" />
        <button type="submit" class="btn btn-warning" asp-page-handler="Clear">Clear</button>
        <a asp-page="DetailedView" asp-route-grantID="@Model.GrantToUpdate.GrantID" class="btn btn-secondary">Cancel</a>
    </div>
</form>