oldSolution/lab484/Pages/Admin/AddProject.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace lab484.Pages.Admin
{
    public class AddProjectModel : PageModel
    {
        [BindProperty]
        public ProjectSimple newProject { get; set; }

        public List<User> facultyList { get; set; } = new List<User>();
        [BindProperty] public List<int> assignedFacultyList { get; set; } = new List<int>();

        // creates new project object and adds faculty to list
        public IActionResult OnGet()
        {
            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            // populate the project variable with info 
            newProject = new ProjectSimple()
            {
                ProjectName = null,
                DueDate = DateTime.Now
            };
            // resets the facList
            facultyList.Clear();

            SqlDataReader facultyReader = DBFaculty.facReader();

            // populate the faculty list to see available people to add 
            while (facultyReader.Read())
            {
                facultyList.Add(new User
                {
                    FirstName = facultyReader["FirstName"].ToString(),
                    LastName = facultyReader["LastName"].ToString(),
                    UserID = Int32.Parse(facultyReader["UserID"].ToString())
                });
            }
            DBFaculty.DBConnection.Close();
            return Page();
        }

        public void OnPost()
        {
            
        }
         
        // add project button 
        public IActionResult OnPostAddProject()
        {
            // adds the project if it has employees selected to work on it 
            if (assignedFacultyList != null && assignedFacultyList.Any())
            {
                DBProject.AddProject(newProject, assignedFacultyList);
            }
            else
            {
                facultyList.Clear();
                SqlDataReader facultyReader = DBFaculty.facReader();
                while (facultyReader.Read())
                {
                    facultyList.Add(new User
                    {
                        FirstName = facultyReader["FirstName"].ToString(),
                        LastName = facultyReader["LastName"].ToString(),
                        UserID = Int32.Parse(facultyReader["UserID"].ToString())
                    });
                }
                DBFaculty.DBConnection.Close();
                return Page();
            }
            DBFaculty.DBConnection.Close();
            return RedirectToPage("AdminLanding");
        }

        // populates the fields 
        public IActionResult OnPostPopulate()
        {
            ModelState.Clear();
            newProject = new ProjectSimple
            {
                ProjectName = "Machine Project",
                DueDate = DateTime.Now,
            };

            //repopulate facultyList
            SqlDataReader facultyReader = DBFaculty.facReader();
            while (facultyReader.Read())
            {
                facultyList.Add(new User
                {
                    FirstName = facultyReader["FirstName"].ToString(),
                    LastName = facultyReader["LastName"].ToString(),
                    UserID = Int32.Parse(facultyReader["UserID"].ToString())
                });
            }
            DBFaculty.DBConnection.Close();

            return Page();
        }

        public IActionResult OnPostClear()
        {
            // Clear the ModelState
            ModelState.Clear();

            // Reset the model properties
            newProject = new ProjectSimple
            {
                DueDate = DateTime.Now
            };
            assignedFacultyList = new List<int>();

            //repopulate facultyList
            SqlDataReader facultyReader = DBFaculty.facReader();
            while (facultyReader.Read())
            {
                facultyList.Add(new User
                {
                    FirstName = facultyReader["FirstName"].ToString(),
                    LastName = facultyReader["LastName"].ToString(),
                    UserID = Int32.Parse(facultyReader["UserID"].ToString())
                });
            }
            DBFaculty.DBConnection.Close();

            return Page();
        }
    }
}

oldSolution/lab484/Pages/Admin/AdminLanding.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace lab484.Pages.Admin
{
    public class AdminLandingModel : PageModel
    {
        public required List<ProjectSimple> projectList { get; set; } = new List<ProjectSimple>();
        [BindProperty]
        public bool DisplayAll { get; set; }
        [BindProperty]
        public String TableButton { get; set; } = "Expand";
        public IActionResult OnGet()
        {
            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            SqlDataReader projectReader = DBProject.ProjectReader();
            while (projectReader.Read())
            {
                // populate the projectList 
                projectList.Add(new ProjectSimple
                {
                    ProjectID = Int32.Parse(projectReader["ProjectID"].ToString()),
                    ProjectName = projectReader["ProjectName"].ToString(),
                    DueDate = DateTime.Parse(projectReader["DueDate"].ToString()),
                    Amount = 0f
                });
                // if the amount isnt a value, try converting it to a string then parsing a float from it 
                if (projectReader["Amount"] != DBNull.Value)
                {
                    if (projectReader["Amount"].ToString() != "")
                    {
                        projectList.Last().Amount = float.Parse(projectReader["Amount"].ToString());
                    }
                    else
                    {
                        projectList.Last().Amount = 0f;
                    }
                }
                else
                {
                    projectList.Last().Amount = 0f;
                }

            }

            // Close your connection in DBClass
            DBProject.DBConnection.Close();
            return Page();
        }

        public IActionResult OnPostToggleTable()
        {

            // method for the collapse / expand button 
            // stores the choice of the user in session state 
            bool DisplayAll = (HttpContext.Session.GetInt32("DisplayAll") == 1);

            // if true, set the button to expand 
            if (DisplayAll)
            {
                TableButton = "Expand";
                HttpContext.Session.SetInt32("DisplayAll", 0);
            }
            // if false set the button title to collapse 
            else
            {
                TableButton = "Collapse";
                HttpContext.Session.SetInt32("DisplayAll", 1);
            }

            // same validation from the top of page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            // loads projects 
            SqlDataReader projectReader = DBProject.ProjectReader();
            while (projectReader.Read())
            {
                // populate the projectList 
                projectList.Add(new ProjectSimple
                {
                    ProjectID = Int32.Parse(projectReader["ProjectID"].ToString()),
                    ProjectName = projectReader["ProjectName"].ToString(),
                    DueDate = DateTime.Parse(projectReader["DueDate"].ToString()),
                    Amount = 0f
                });
                // if the amount isnt a value, try converting it to a string then parsing a float from it 
                if (projectReader["Amount"] != DBNull.Value)
                {
                    if (projectReader["Amount"].ToString() != "")
                    {
                        projectList.Last().Amount = float.Parse(projectReader["Amount"].ToString());
                    }
                    else
                    {
                        projectList.Last().Amount = 0f;
                    }
                }
                else
                {
                    projectList.Last().Amount = 0f;
                }
            }
            DBProject.DBConnection.Close();
            return Page();
        }
    }
}

oldSolution/lab484/Pages/Admin/BPDetail.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace lab484.Pages.Admin
{
    public class BPDetailModel : PageModel
    {
        public BusinessPartner BP {  get; set; }


        public IActionResult OnGet()
        {
            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            SqlDataReader BPReader = DBGrantSupplier.BPReader();
            BP = new BusinessPartner();

            // gets the bp id 
            while (BPReader.Read())
            {
                BP.SupplierID = Convert.ToInt32(BPReader["SupplierID"].ToString());
            }
            DBGrantSupplier.DBConnection.Close();

            return Page();
        }
    }
}

oldSolution/lab484/Pages/Admin/ProjectAssociateFac.cshtml.cs
using lab484.Pages.DB;
using lab484.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Diagnostics;

namespace lab484.Pages.Admin
{
    public class ProjectAssociateFacModel : PageModel
    {
        [BindProperty]
        public int GrantID { get; set; }
        [BindProperty]
        public int ProjectID { get; set; }

        // make variable so we can access it w/o reading list 
        public string ProjectName { get; set; }
        public required List<ProjectStaff> StaffList { get; set; } = new List<ProjectStaff>();
        public List<User> UserList { get; set; } = new List<User>();

        public IActionResult OnGet(int ProjectID)
        {
            StaffList.Clear();

            // control validating if the user is an admin trying to access the page 
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("facultyStatus") != 1 && HttpContext.Session.GetInt32("adminStatus") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }

            this.ProjectID = ProjectID;  // sets the ProjectID

            // populates the ProjectName variable so it can be used
            // checks if there are any staff in list first
            SqlDataReader projectReader = DBProject.singleProjectReader(this.ProjectID);
            if (projectReader.Read())
            {
                this.ProjectName = projectReader["ProjectName"].ToString();
            }
            DBProject.DBConnection.Close();

            SqlDataReader facultyReader = DBFaculty.singleProjectFacultyReader(ProjectID);
            while (facultyReader.Read())
            {
                StaffList.Add(new ProjectStaff
                {
                    UserID = Int32.Parse(facultyReader["UserID"].ToString()),
                    Username = facultyReader["Username"].ToString(),
                    FirstName = facultyReader["FirstName"].ToString(),
                    LastName = facultyReader["LastName"].ToString(),
                    Email = facultyReader["Email"].ToString(),
                    Phone = facultyReader["Phone"].ToString(),
                    HomeAddress = facultyReader["HomeAddress"].ToString(),
                    ProjectID = Int32.Parse(facultyReader["ProjectID"].ToString()),
                    ProjectName = facultyReader["ProjectName"].ToString(),
                    Leader = bool.Parse(facultyReader["Leader"].ToString()),
                    Active = bool.Parse(facultyReader["Active"].ToString())
                });
            }
            DBFaculty.DBConnection.Close();

            // as long as there are faculty in the db for the method to read from the user will be added to the userList 
            using (SqlDataReader facReader = DBFaculty.facReader())
            {
                while (facReader.Read())
                {
                    UserList.Add(new User
                    {
                        UserID = Int32.Parse(facReader["UserID"].ToString()),
                        UserName = facReader["Username"].ToString()
                    });
                }
            }

            // Close your connection in DBClass
            DBFaculty.DBConnection.Close();
            return Page();
        }

        public IActionResult OnPostAddFaculty(int UserID)
        {
            // Retrieve the User object based on UserID
            User user = DBClass.GetUserByID(UserID);

            SqlDataReader projectReader = DBProject.singleProjectReader(this.ProjectID);
            if (projectReader.Read())
            {
                this.ProjectName = projectReader["ProjectName"].ToString();
            }
            DBProject.DBConnection.Close();

            if (user != null)
            {
                // why does ProjectID keep showing as 0 omg 
                DBProject.InsertProjectStaff(user, this.ProjectID);
            }


            // reloads the page 
            return RedirectToPage(new {ProjectID = this.ProjectID});

        }
    }
}

oldSolution/lab484/Pages/Admin/TaskDetail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace lab484.Pages.Admin
{
    public class TaskDetailModel : PageModel
    {
        public int taskID { get; set; }
        public void OnGet(int taskID)
        {
            this.taskID = taskID;
        }
    }
}

oldSolution/lab484/Pages/Admin/AddProject.cshtml
@page
@model lab484.Pages.Admin.AddProjectModel
@{
}
<head>
	<meta charset="utf-8" />
	<title>Add Project</title>
</head>
<br />
<h2 class="text-center">Add a Project</h2>
<br />
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <p>@error.ErrorMessage</p>
        }
    </div>
}

<form method="post" class="form-horizontal">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newProject.ProjectName">Project Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="newProject.ProjectName" required/>
            <span class="text-danger" asp-validation-for="newProject.ProjectName"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newProject.DueDate">Submission Date</label>
        <div class="col-sm-10">
            <input type="date" class="form-control" asp-for="newProject.DueDate" required/>
            <span class="text-danger" asp-validation-for="newProject.DueDate"></span>
        </div>
    </div>
    <br />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Associate Faculty</label>
        <div class="col-sm-10">
            @foreach (var faculty in Model.facultyList)
            {
                <div class="form-check d-block">
                    <input type="checkbox" class="form-check-input" name="assignedFacultyList" value="@faculty.UserID" id="@faculty.UserID" />
                    <label class="form-check-label" for="@faculty.UserID">@faculty.FirstName @faculty.LastName</label>
                </div>
            }
        </div>
    </div>
    <br />
    <div class="text-center">
        <input type="submit" class="btn btn-outline-primary" asp-page-handler="AddProject" value="Add Project" />
        <button type="submit" class="btn btn-outline-secondary" asp-page-handler="Clear" formnovalidate>Clear</button>
        <a asp-page="AdminLanding" class="btn btn-secondary">Cancel</a>
        <br /><br />
    </div>
</form>

<div class="text-center">
    <form method="post">
        <button type="submit" class="btn btn-outline-primary" asp-page-handler="Populate">Populate</button>
    </form>
</div>

oldSolution/lab484/Pages/Admin/AddProjectNote.cshtml
@page "{ProjectID:int}"
@model lab484.Pages.Admin.AddProjectNoteModel
@{
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
        {
            <p>@error.ErrorMessage</p>
        }
    </div>
}

<head>
    <meta charset="utf-8" />
    <title>Add Project Note for </title>
</head>
<br />
<h2 class="text-center">Add a Project Note</h2>
<br />
<form method="post" class="form-horizontal">
    <input type="hidden" asp-for="newProjectNote.ProjectID" value="@Model.newProjectNote.ProjectID" />
    <input type="hidden" asp-for="newProjectNote.AuthorFirst" value="@Model.user.FirstName" />
    <input type="hidden" asp-for="newProjectNote.AuthorLast" value="@Model.user.LastName" />
    <input type="hidden" asp-for="newProjectNote.AuthorID" value="@Model.user.UserID" />
    <input type="hidden" asp-for="newProjectNote.TimeAdded" value="@Model.newProjectNote.TimeAdded" />
    <div class="form-group row">
        <label class="col-sm-2 col-form-label" asp-for="newProjectNote.Content">Content</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="newProjectNote.Content" required />
            <span class="text-danger" asp-validation-for="newProjectNote.Content"></span>
        </div>
    </div>
    <br />
    <div class="text-center">
        <button type="submit" class="btn btn-outline-primary">Submit</button>
        <button type="submit" class="btn btn-outline-secondary" asp-page-handler="Clear" formnovalidate>Clear</button>
        <a asp-page="ProjectDetail" asp-route-projectID="@Model.ProjectID" class="btn btn-secondary">Cancel</a>
        <br /><br />
    </div>
</form>

oldSolution/lab484/Pages/Admin/AdminLanding.cshtml
@page
@model lab484.Pages.Admin.AdminLandingModel
@{
}
<head>
    <meta charset="utf-8" />
    <title>Projects</title>
</head>
<br />
<h2 class="text-center">Available Projects</h2>
<br />
<table class="table table-bordered table-responsive table-hover">
    <thead>
        <tr>
            <th>Project Name</th>
            <th>Due Date</th>
            <th>Funding</th>
            <th>Detailed View</th>
        </tr>
    </thead>
    <tbody>
        @{
            int iteration = 0;
            if (Model.HttpContext.Session.GetInt32("DisplayAll") == 1)
            {
                foreach (var project in @Model.projectList)
                {
                    <tr>
                        <td>@project.ProjectName</td>
                        <td>@project.DueDate.ToString("MM/dd/yyyy")</td> <! -- formats as date, no time !>
                        <td>@string.Format("{0:C}", project.Amount)</td> <! -- formats as dollar value !>
                        <td>
                            <div class="text-center">
                                <a class="btn btn-outline-primary" asp-page="/Admin/ProjectDetail" asp-route-ProjectID="@project.ProjectID">Detailed View</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                foreach (var project in @Model.projectList)
                {
                    if (iteration < 5)
                    {
                        <tr>
                            <td>@project.ProjectName</td>
                            <td>@project.DueDate.ToString("MM/dd/yyyy")</td> <! -- formats as date, no time !>
                            <td>@string.Format("{0:C}", project.Amount)</td> <! -- formats as dollar value !>
                            <td>
                                <div class="text-center">
                                    <a class="btn btn-outline-primary" asp-page="/Admin/ProjectDetail" asp-route-ProjectID="@project.ProjectID">Detailed View</a>
                                </div>
                            </td>
                        </tr>
                        iteration++;
                    }
                    else { break; }
                }
            }
        }
    </tbody>
</table>
<div class="text-center">
    <form method="post">
        @{
            if (Model.projectList.Count() > 5)
            {
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-secondary" asp-page-handler="ToggleTable">@Model.TableButton</button>
                </div>
            }
        }
    </form>
    <br />
    <a class="btn btn-outline-primary" asp-page="AddProject">Add Project</a>
    <a class="btn btn-outline-primary" asp-page="BusinessPartners">View Business Partners</a>
</div>

oldSolution/lab484/Pages/Admin/BPDetail.cshtml
@page
@model lab484.Pages.Admin.BPDetailModel
@{
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Partner Details</title>
</head>
<body>
    <div class="table-container">
        <div class="details-container">
            <h2>Partner Details</h2>
            <table>
                <tr>
                    <th>Partner Name</th>
                    <td id="partner-name">Federal Bureau of Investigation</td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>Active Partner</td>
                </tr>
                <tr>
                    <th>Primary Contact</th>
                    <td>John Smith</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>johnsmith@gmail.com</td>
                </tr>
                <tr>
                    <th>Phone</th>
                    <td>(123) 456-7890</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>935 Pennsylvania Ave NW, Washington, DC</td>
                </tr>
                <tr>
                    <th>Notes</th>
                    <td>
                        - The FBI collaborates on national security and intelligence initiatives.
                        <br>- Meeting next Monday
                        <br>- Talk about the stuff
                    </td>
                </tr>
            </table>
            <br>
        </div>
    </div>
</body>
<a class="btn btn-outline-primary" asp-page="BusinessPartners">Return to Partners</a>

oldSolution/lab484/Pages/Admin/BusinessPartners.cshtml
@page
@model lab484.Pages.Admin.BusinessPartnersModel
@{
}
<head>
    <meta charset="utf-8" />
    <title>Business Partners</title>
</head>
<div>
    <br />
    <h2 class="text-center">Partners</h2>
    <br />
    <table class="table table-bordered table-responsive table-hover">
        <thead>
            <tr>
                <th>Business Partner</th>
                <th>Status</th>
                <th>Primary Contact</th>
                <th>Contact</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var bp in @Model.bpList)
                {
                    <tr>
                        <td>@bp.SupplierName</td>
                        <td>@bp.SupplierStatus</td>
                        <td>@bp.FirstName @bp.LastName</td>
                        <td>@bp.Email</td>
                        <td>
                            <div class="text-center">
                                <a class="btn btn-outline-primary" asp-page="BPDetail">Detailed View</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            
        </tbody>
    </table>
    <div class="text-center">
        <a class="btn btn-outline-primary" asp-page="AdminLanding">Return to Projects</a>
    </div>
    
</div>

oldSolution/lab484/Pages/Admin/ProjectAssociateFac.cshtml
@page "{ProjectID:int}"
@model lab484.Pages.Admin.ProjectAssociateFacModel

@{
}
<div>
    <h2>
        @Model.ProjectName
    </h2>
</div>
<br />
<h2 class="text-center">Project Staff</h2>
<br />
<table class="table table-striped table-hover">
    <thead class="thead-light">
        <tr>
            <th >Username</th>
            <th >Last Name</th>
            <th >Email</th>
            <th >First Name</th>
            <th >Phone</th>
            <th >Leader</th>
            <th >Active</th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.StaffList.Any())
        {
            <tr>
                <td colspan="7" class="text-center">There are no faculty members working on this project.</td>
            </tr>
        }
        else
        {
            @foreach (var staff in Model.StaffList)
            {
                <tr>
                    <td>@staff.Username</td>
                    <td>@staff.FirstName</td>
                    <td>@staff.LastName</td>
                    <td>@staff.Email</td>
                    <td>@staff.Phone</td>
                    <td>@staff.Leader</td>
                    <td>@staff.Active</td>
                </tr>
            }
        }
    </tbody>
</table>

<div class="mt-3">
    <form method="post" asp-page-handler="AddFaculty">
        <input type="hidden" asp-for="ProjectID" />
        <input type="hidden" asp-for="GrantID" />
        <div class="form-group">
            <label for="UserID">Select Faculty Member to associate:</label>
            <select id="UserID" name="UserID" class="form-control">
                @foreach (var user in @Model.UserList)
                {
                    <option value="@user.UserID">@user.UserName</option>
                }
            </select>
        </div>
        <br />
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Associate Faculty</button>
        </div>
    </form>
</div>

<br />

<div class="text-center">
    <a class="btn btn-outline-primary" asp-page="ProjectDetail" asp-route-projectID="@Model.ProjectID">Back to Details</a>
</div>

oldSolution/lab484/Pages/Admin/ProjectDetail.cshtml
@page "{projectID:int}"
@model lab484.Pages.Admin.ProjectDetailModel
@{
}
<head>
	<meta charset="utf-8" />
	<title>Project Name</title>
</head>
<br />
<h2 class="text-center">@Model.project.ProjectName  s</h2>
<br />

<!-- Used AI for some formatting-->
<div class="container mt-4 p-4 border rounded bg-light">
	<h3>Project Staff</h3>
	<table class="table table-bordered table-responsive table-hover bg-white">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Phone</th>
				<th>Drop from Project</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var projectStaff in Model.userProjectList)
			{
				<tr>
					<td>@projectStaff.FirstName @projectStaff.LastName</td>
					<td>@projectStaff.Email</td>
					<td>@projectStaff.Phone</td>
					<td>
						<a class="btn btn-outline-primary">Remove from Project</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
	<div>
		<a class="btn btn-outline-primary" asp-page="/Admin/ProjectAssociateFac" asp-route-ProjectID="@Model.projectID">Add/Edit Staff</a>
	</div>
</div>

<br />

<!-- Used AI for some formatting-->
<div class="container mt-4 p-4 border rounded bg-light">
	<h3>Tasks</h3>
	<table class="table table-bordered table-responsive table-hover bg-white">
		<thead>
			<tr>
				<th>Objective</th>
				<th>Due Date</th>
				<th>Staff</th>
				<th>Detailed View</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var task in Model.taskList)
			{
				<tr>
					<td>@task.Objective</td>
					<td>@task.DueDate.ToString("MM/dd/yyyy")</td>
					<td>
						<select class="form-select">
							<option value="x">View Staff</option>
							@foreach (var staffer in Model.userTaskList)
							{
								<option value="x">@staffer.FirstName @staffer.LastName</option>
							}
						</select>
					</td>
					<td class="text-center">
						<a class="btn btn-outline-primary" asp-page="/Admin/TaskDetail" asp-route-taskID="@task.TaskID">Detailed View</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

<br />

<div class="container mt-4 p-4 border rounded bg-light">
	<h3>Project Notes</h3>
	<table class="table table-bordered table-responsive table-hover bg-white">
		<thead>
			<tr>
				<th>Note</th>
				<th>Author</th>
				<th>Date Added</th>
			</tr>
		</thead>
		<tbody>
			@{
				foreach (var note in Model.noteList)
				{
					<tr>
						<td>@note.Content</td>
						<td>@note.AuthorFirst @note.AuthorLast</td>
						<td>@note.TimeAdded</td>
					</tr>
				}
			}
		</tbody>
	</table>

	<div>
		<a class="btn btn-outline-primary" asp-page="AddProjectNote" asp-route-projectID="@Model.projectID">Add Note</a>
	</div>

<br />
<div class="text-center">
	<a class="btn btn-outline-primary" asp-page="AdminLanding">Return to Projects</a>
</div>
</div>

oldSolution/lab484/Pages/Admin/TaskDetail.cshtml
@page
@model lab484.Pages.Admin.TaskDetailModel
@{
}

<h2></h2>