CAREapplication/WebApplication1/Pages/BusinessPartners.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using CAREapplication.Pages.DB;

using CAREapplication.Pages.DataClasses;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace CAREapplication.Pages
{
    public class BusinessPartnersModel : PageModel
    {
        public required List<BusinessPartner> funderList { get; set; } = new List<BusinessPartner>();

        [BindProperty]
        [Required(ErrorMessage = "You must have a search term.")]
        public String searchTerm { get; set; }

        public required List<BusinessPartner> searchedBPList { get; set; } = new List<BusinessPartner>();

        public IActionResult OnGet()
        {
            // Validate if the user is an admin trying to access the page
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/Index"); // Redirect to login page
            }
            else if (HttpContext.Session.GetInt32("director") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You do not have permission to access that page!");
                return RedirectToPage("/Index"); // Redirect to login page
            }

            // Populate BusinessPartners to be shown in the view
            SqlDataReader FunderReader = DBFunder.FunderReader();
            while (FunderReader.Read())
            {
                funderList.Add(new BusinessPartner
                {
                    FunderID = int.Parse(FunderReader["FunderID"].ToString()),
                    FunderName = FunderReader["FunderName"].ToString(),
                    FunderStatus = FunderReader["StatusName"].ToString(),
                    OrgType = FunderReader["OrgType"].ToString(),
                    BusinessAddress = FunderReader["BusinessAddress"].ToString(),

                    // Use POC values instead of rep
                    FirstName = FunderReader["POCFirstName"].ToString(),
                    LastName = FunderReader["POCLastName"].ToString(),
                    Email = FunderReader["POCEmail"].ToString(),
                    Phone = FunderReader["POCPhone"].ToString(),
                    HomeAddress = FunderReader["POCAddress"].ToString(),
                    CommunicationStatus = FunderReader["POCCommStatus"].ToString()

                });
            }
            DBFunder.DBConnection.Close();
            return Page();
        }

        public IActionResult OnPostSearch()
        {
            ModelState.Clear();

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                Trace.WriteLine("AAAAAAAAAAAAHHHHHHHHHHHH");
                ModelState.AddModelError("searchTerm", "Search term cannot be empty.");
                SqlDataReader BPsearch = DBFunder.BPSearch(searchTerm);
                while (BPsearch.Read())
                {
                    searchedBPList.Add(new BusinessPartner
                    {
                        UserID = Int32.Parse(BPsearch["UserID"].ToString()),
                        FirstName = BPsearch["FirstName"].ToString(),
                        LastName = BPsearch["LastName"].ToString(),
                        Email = BPsearch["Email"].ToString(),
                        Phone = BPsearch["Phone"].ToString(),
                        HomeAddress = BPsearch["HomeAddress"].ToString(),
                        CommunicationStatus = BPsearch["CommunicationStatus"].ToString(),
                        FunderID = Int32.Parse(BPsearch["FunderID"].ToString()),
                        FunderName = BPsearch["FunderName"].ToString(),
                        OrgType = BPsearch["OrgType"].ToString(),
                        FunderStatus = BPsearch["StatusName"].ToString()
                    });
                }
                DBFunder.DBConnection.Close(); // Load all projects so they still display
                return Page();
            }

            return Page();
        }
    }
}

CAREapplication/WebApplication1/Pages/DetailedBusinessPartners.cshtml.cs
using CAREapplication.Pages.DataClasses;
using CAREapplication.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Reflection;


namespace CAREapplication.Pages
{


    public class DetailedBusinessPartnersModel : PageModel
    {
        public BusinessPartner funder { get; set; }
        public FunderNote note { get; set; }
        public IActionResult OnGet(int FunderID)
        {
            // Validate if the user is an admin trying to access the page
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("/Index"); // Redirect to login page
            }

            note = new FunderNote();
            using (SqlDataReader reader = DBFunder.SingleNoteReader(FunderID))
            {
                if (reader.Read())
                {
                    note.Contents = reader["Contents"].ToString();
                    note.DateAdded = DateTime.Parse(reader["DateAdded"].ToString());
                    note.FirstName = reader["FirstName"].ToString();
                    note.LastName = reader["LastName"].ToString();
                }
                reader.Close();

            }

            funder = new BusinessPartner();
            using (SqlDataReader reader = DBFunder.SingleFunderReader(FunderID))
            {
                if (reader.Read())
                {
                    funder.FunderID = Convert.ToInt32(reader["FunderID"]);
                    funder.FunderName = reader["FunderName"].ToString();
                    funder.OrgType = reader["OrgType"].ToString();
                    funder.BusinessAddress = reader["BusinessAddress"].ToString();
                    funder.CommunicationStatus = reader["CommunicationStatus"] != DBNull.Value
                        ? reader["CommunicationStatus"].ToString()
                        : "N/A";
                    funder.FunderStatus = reader["StatusName"]?.ToString() ?? "Unknown";
                    funder.FirstName = reader["FirstName"].ToString();
                    funder.LastName = reader["LastName"].ToString();
                    funder.Email = reader["Email"].ToString();
                    funder.Phone = reader["Phone"].ToString();
                    funder.HomeAddress = reader["HomeAddress"].ToString();
                    funder.City = reader["City"].ToString();
                    funder.HomeState = reader["HomeState"].ToString();
                    funder.Zip = reader["Zip"].ToString();
                    funder.funderPOCID = Convert.ToInt32(reader["funderPOCID"]);
                }
                reader.Close();

            }
            DBFunder.DBConnection.Close();

            return Page();
        }
        public IActionResult OnPostUpdateCommStatus(int? funderPOCID, String? CommunicationStatus)
        {
            try
            {
                DBFunder.UpdateCommStatus(funderPOCID.Value, CommunicationStatus);
            }
            catch (SqlException ex)
            {
                Trace.WriteLine($"SQL Error (Update Task): {ex.Message}");
                ModelState.AddModelError("", "Error updating task: " + ex.Message);
            }

            return RedirectToPage(new { FunderID = funderPOCID });
        }

    }
}

CAREapplication/WebApplication1/Pages/Index.cshtml.cs
using System.Diagnostics;
using CAREapplication.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages;

public class IndexModel : PageModel
{
    [BindProperty]
    public string Username { get; set; }

    [BindProperty]
    public string Password { get; set; }

    public IActionResult OnGet(string logout)
    {
        if (logout == "true")
        {
            HttpContext.Session.Clear();
            ViewData["LogoutMessage"] = "Successfully Logged Out!";
        }

        // Check for stored login error messages
        string loginError = HttpContext.Session.GetString("LoginError");
        if (!string.IsNullOrEmpty(loginError))
        {
            ViewData["LoginMessage"] = loginError;
            HttpContext.Session.Remove("LoginError"); // Clear after displaying
        }

        string logoutMessage = HttpContext.Session.GetString("LogoutMessage");
        if (!string.IsNullOrEmpty(logoutMessage))
        {
            ViewData["LogoutMessage"] = logoutMessage;
            HttpContext.Session.Remove("LogoutMessage"); // Clear after displaying
        }


        return Page();
    }

    public IActionResult OnPost()
    {
        if (DBClass.UserCheck(Username))
        {
            if (DBClass.HashedLogin(Username, Password))
            {
                DBClass.DBConnection.Close();
                HttpContext.Session.SetInt32("loggedIn", 1);
                HttpContext.Session.SetString("username", Username);

                // Retrieve user ID
                int userID = DBClass.HashedUserID(Username);
                HttpContext.Session.SetInt32("userID", userID);
                DBClass.DBConnection.Close();

                // Check user permissions
                int director = DBClass.directorCheck(userID);
                DBClass.DBConnection.Close();

                int adminAssistant = DBClass.adminAsstCheck(userID);
                DBClass.DBConnection.Close();

                if (director == 1)
                {
                    HttpContext.Session.SetInt32("director", 1);
                    return RedirectToPage("/Users/UserDashboard");
                }
                else if (adminAssistant == 1)
                {
                    HttpContext.Session.SetInt32("adminAsst", 1);
                    return RedirectToPage("/Users/UserDashboard");
                }
                else { return RedirectToPage("/Users/UserDashboard"); }
            }
            else
            {
                ViewData["LoginMessage"] = "Username and/or Password Incorrect";
                return Page();
            }
        }
        else
        {
            ViewData["LoginMessage"] = "Username and/or Password Incorrect";
            return Page();
        }
    }

    public IActionResult OnPostLogoutHandler()
    {
        HttpContext.Session.SetString("LogoutMessage", "Successfully logged out.");
        return RedirectToPage("Index");
    }
}

CAREapplication/WebApplication1/Pages/MessageConvo.cshtml.cs
using CAREapplication.Pages.DataClasses;
using CAREapplication.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Reflection;

namespace CAREapplication.Pages
{

    public class MessageConvoModel : PageModel
    {
        public required List<Message> receivedList { get; set; } = new List<Message>();
        public User otherUser { get; set; } = new User();
        public List<SelectListItem> Usernames { get; set; } = new List<SelectListItem>();
        [BindProperty]
        [Required(ErrorMessage = "Must include message content.")]
        public string MessageContent { get; set; }

        public string currentuser { get; set; } 
        

        public IActionResult OnGet(int sender)
        {
            if (HttpContext.Session.GetInt32("loggedIn") != 1)
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("../Index"); // Redirect to login page
            }
            currentuser = HttpContext.Session.GetString("username");
            Usernames = new List<SelectListItem>();

            // Execute the userReader method from DBClass to load the usernames 
            using (SqlDataReader reader = DBClass.UserReader())
            {
                while (reader.Read())
                {
                    if (!(reader["Username"].ToString()).Equals(currentuser))
                    {
                        Usernames.Add(new SelectListItem
                        {
                            Value = reader["UserID"].ToString(),
                            Text = reader["Username"].ToString()
                        });
                    }
                    
                }
                reader.Close();
                DBClass.DBConnection.Close();
            }

            Trace.WriteLine(sender); // works 

            otherUser = DBClass.GetUserByID(sender);

            LoadReceivedMessages(HttpContext.Session.GetInt32("userID"), otherUser.UserID);

            Trace.WriteLine(receivedList.Count);


    
            return Page();
        }

        public IActionResult OnPost(int sender)
        {
            Trace.WriteLine("Executed OnPost");

            Usernames = new List<SelectListItem>();

            // Execute the userReader method from DBClass to load the usernames 
            using (SqlDataReader reader = DBClass.UserReader())
            {
                while (reader.Read())
                {
                    if (!(reader["Username"].ToString()).Equals(currentuser))
                    {
                        Usernames.Add(new SelectListItem
                        {
                            Value = reader["UserID"].ToString(),
                            Text = reader["Username"].ToString()
                        });
                    }

                }
                reader.Close();
                DBClass.DBConnection.Close();
            }

            Trace.WriteLine(sender); // works 

            otherUser = DBClass.GetUserByID(sender);

            LoadReceivedMessages(HttpContext.Session.GetInt32("userID"), otherUser.UserID);

            Trace.WriteLine(receivedList.Count);

            return Page();
        }

        public IActionResult OnPostSendMessage(int sender)
        {
            Trace.WriteLine("Executed SendMessage");

            Usernames = new List<SelectListItem>();

            // Execute the userReader method from DBClass to load the usernames 
            using (SqlDataReader reader = DBClass.UserReader())
            {
                while (reader.Read())
                {
                    if (!(reader["Username"].ToString()).Equals(currentuser))
                    {
                        Usernames.Add(new SelectListItem
                        {
                            Value = reader["UserID"].ToString(),
                            Text = reader["Username"].ToString()
                        });
                    }

                }
                reader.Close();
                DBClass.DBConnection.Close();
            }

            Trace.WriteLine(sender); // works 

            otherUser = DBClass.GetUserByID(sender);

            LoadReceivedMessages(HttpContext.Session.GetInt32("userID"), otherUser.UserID);

            if (MessageContent != null)
            {
                DBMessage.InsertUserMessage(HttpContext.Session.GetInt32("userID"), otherUser.UserID, MessageContent);
            }

            ModelState.Clear();
            MessageContent = string.Empty;

            LoadReceivedMessages(HttpContext.Session.GetInt32("userID"), otherUser.UserID);

            Trace.WriteLine(receivedList.Count);

            return Page();
        }

        private void LoadReceivedMessages(int? recipient, int sender)
        {
            receivedList = new List<Message>();

            using (SqlDataReader receivedReader = DBMessage.singleConvoReader(recipient, sender))
            {
                while (receivedReader.Read())
                {
                    receivedList.Add(new Message
                    {
                        SenderID = int.Parse(receivedReader["SenderID"].ToString()),
                        SenderUsername = receivedReader["SenderUsername"].ToString(),
                        RecipientID = int.Parse(receivedReader["RecipientID"].ToString()),
                        RecipientUsername = receivedReader["RecipientUsername"].ToString(),
                        SubjectTitle = receivedReader["SubjectTitle"].ToString(),
                        Contents = receivedReader["Contents"].ToString(),
                        MessageID = int.Parse(receivedReader["MessageID"].ToString()),
                        SentTime = DateTime.Parse(receivedReader["SentTime"].ToString())
                    });
                }
                receivedReader.Close();
            }
            DBMessage.DBConnection.Close();
        }
    }
}

CAREapplication/WebApplication1/Pages/BusinessPartners.cshtml
@page
@model CAREapplication.Pages.BusinessPartnersModel
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Business Partners</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- LOAD BOOTSTRAP CSS - DO NOT DELETE -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="styles.css" rel="stylesheet">
    <!-- END LOADING BOOTSTRAP CSS -->
    <!-- Custom styles -->
    <link href="/css/business.partners.dash.custom.css" rel="stylesheet">
</head>

<body>
    <!-- Main Content -->
    <div class="container-fluid py-5 main-bg">
        <div class="container main-container">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h2>BUSINESS PARTNERS DASHBOARD</h2>
                <form method="post" class="d-flex align-items-center gap-2">
                    <input type="search" asp-for="searchTerm" class="form-control w-auto" placeholder="Search" />
                    <button asp-page-handler="Search" class="btn search-btn">Search</button>
                </form>
            </div>

            <!-- Table Header (no spacing) -->
            <div class="table-container">
                <table class="table text-center align-middle table-bordered header-table">
                    <thead>
                        <tr>
                            <th>PARTNER</th>
                            <th>ORGANIZATION TYPE</th>
                            <th>STATUS</th>
                            <th>PRIMARY CONTACT</th>

                            <th>DETAILED VIEW</th>
                        </tr>
                    </thead>
                </table>

                <!-- Dynamic Project Table -->
                <div class="table-scroll">
                    <table class="table text-center align-middle table-bordered table-body mt-0">
                        <tbody>
                            @if (Model.searchedBPList != null && Model.searchedBPList.Count > 0)
                            {
                                foreach (var bp in Model.searchedBPList)
                                {
                                    <tr class="project-row">
                                        <td class="fw-bold">@bp.FunderName</td>
                                        <td>@bp.OrgType</td>
                                        <td>@bp.FunderStatus</td>
                                        <td>@bp.FirstName @bp.LastName</td>
                                        <td><a class="btn sm-btn" asp-route-FunderID="@bp.FunderID" asp-page="DetailedBusinessPartners">DETAILED VIEW</a></td>
                                    </tr>
                                }
                            }
                            else if (!string.IsNullOrWhiteSpace(Model.searchTerm))
                            {
                                <tr>
                                    <td colspan="5" class="text-center fw-bold text-danger">No results found.</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var bp in Model.funderList)
                                {
                                    <tr class="project-row">
                                        <td class="fw-bold">@bp.FunderName</td>
                                        <td>@bp.OrgType</td>
                                        <td>@bp.FunderStatus</td>
                                        <td>@bp.FirstName @bp.LastName</td>
                                        <td><a class="btn sm-btn" asp-route-FunderID="@bp.FunderID" asp-page="DetailedBusinessPartners">DETAILED VIEW</a></td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Large Buttons -->
            <div class="d-flex justify-content-end gap-3 mt-3">
                <a class="btn lg-btn" asp-page="/Project/ProjectDashboard">BACK TO PROJECT DASHBOARD</a>
            </div>
        </div>
    </div>

</body>
</html>

CAREapplication/WebApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    Layout = null;
    ViewData["Title"] = "Home page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>JMU CARE Login</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/login.css" rel="stylesheet">
</head>

<body class="d-flex justify-content-center align-items-center" style="height: 100vh;">

    <div class="login-container">
        <img src="/images/JMU.Care.png" alt="JMU CARE Logo" class="logo mb-4">

        <!-- Error Message Display -->
        @{
            if (ViewData["LoginMessage"] != null)
            {
                <div class="alert alert-danger text-center">
                    @ViewData["LoginMessage"]
                </div>
            }
            else if (ViewData["LogoutMessage"] != null)
            {
                <div class="alert alert-success text-center">
                    @ViewData["LogoutMessage"]
                </div>
            }
        }

        <form method="post">
            <input asp-for="Username" type="text" class="form-control mb-3" placeholder="USERNAME" required>
            <input asp-for="Password" type="password" class="form-control mb-3" placeholder="PASSWORD" required>
            <button type="submit" class="btn-login btn btn-primary">LOGIN</button>
        </form>
    </div>

</body>
</html>

CAREapplication/WebApplication1/Pages/MessageConvo.cshtml
@page
@using System.Diagnostics
@model CAREapplication.Pages.MessageConvoModel
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Scrolling Nav - Start Bootstrap Template 5.3.3</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- LOAD BOOTSTRAP CSS - DO NOT DELETE -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="styles.css" rel="stylesheet">
    <!-- END LOADING BOOTSTRAP CSS -->
    <!-- Custom styles -->
    <link href="/css/messages.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid main-container">
        <div class="row g-2">
            <!-- Add a small gap between columns using Bootstrap's grid gap utilities -->
            <div class="col-12 col-md-3 sidebar mt-5">
                <div class="sidebar-scroll p-3">
                    <h5 class="mb-3">RECENT MESSAGES</h5>
                    <input type="text" class="form-control mb-3" placeholder="Search">

                    <ul class="list-group message-list">
                        @foreach (var username in Model.Usernames)
                        {
                            if (username.Text != Model.currentuser)
                            {
                                <li class="list-group-item">
                                    <a class="list-group-item" asp-page="MessageConvo" asp-route-sender="@username.Value">@username.Text</a>
                                </li>
                            }
                        }
                    </ul>

                    <div class="mt-3">
                        <button class="btn btn-primary w-100">NEW MESSAGE</button>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-7 chat-sidebar p-3 mt-5">
                <!-- Chat container with 9 columns on medium screens -->
                @if (Model.receivedList.Count > 0)
                {
                    <div class="chat-header d-flex align-items-center">
                        <div class="avatar">
                            @if (!string.IsNullOrEmpty(Model.otherUser.FirstName) && !string.IsNullOrEmpty(Model.otherUser.LastName))
                            {
                                @Model.otherUser.FirstName.Substring(0, 1)

                                @Model.otherUser.LastName.Substring(0, 1)
                            }
                            else
                            {
                                <span>NA</span> <!-- Default value if FirstName or LastName is null -->
                            }
                        </div>
                        <h5 class="ms-2">@Model.otherUser.UserName</h5>
                    </div>
                    <br />
                    <div class="chat-box">
                        @foreach (var message in Model.receivedList)
                        {
                            <div class="message @(message.SenderUsername == Model.otherUser.UserName ? "bg-light text-dark" : "bg-secondary text-white") p-2 rounded">
                                <strong>@message.SenderUsername:</strong> @message.Contents
                            </div>
                        }

                    </div>
                }
                else
                {
                    <div class="chat-header d-flex align-items-center">
                        <div class="avatar">
                            @if (!string.IsNullOrEmpty(Model.otherUser.FirstName) && !string.IsNullOrEmpty(Model.otherUser.LastName))
                            {
                                @Model.otherUser.FirstName.Substring(0, 1)

                                @Model.otherUser.LastName.Substring(0, 1)
                            }
                            else
                            {
                                <span>NA</span> <!-- Default value if FirstName or LastName is null -->
                            }
                        </div>
                        <h5 class="ms-2">@Model.otherUser.UserName</h5>
                    </div>
                    <br />
                    <div class="chat-box">
                        <p>No messages to display.</p>
                    </div>
                }

                <form method="post">
                    <div class="chat-input d-flex">
                        <input asp-for="MessageContent" type="text" class="chat-input form-control" placeholder="Type a message">
                        
                        <button asp-page-handler="SendMessage" asp-route-sender="@Model.otherUser.UserID" type=" submit" class="btn btn-primary ms-2">Send</button>
                    </div>
                    
                    <span asp-validation-for="MessageContent" class="text-danger"></span>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

CAREapplication/WebApplication1/Pages/Messages.cshtml
@page
@model CAREapplication.Pages.MessagesModel
@{
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Scrolling Nav - Start Bootstrap Template 5.3.3</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- LOAD BOOTSTRAP CSS - DO NOT DELETE -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="styles.css" rel="stylesheet">
    <!-- END LOADING BOOTSTRAP CSS -->
    <!-- Custom styles -->
    <link href="/css/messages.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid main-container">
        <div class="row g-2">
            <!-- Add a small gap between columns using Bootstrap's grid gap utilities -->
            <div class="col-12 col-md-3 sidebar mt-5">
                <div class="sidebar-scroll p-3">
                    <h5 class="mb-3">RECENT MESSAGES</h5>

                    <input type="text" class="form-control mb-3" placeholder="Search">

                    <ul class="list-group message-list">
                        @foreach (var username in Model.Usernames)
                        {
                            if (username.Text != Model.usr)
                            {
                                <li class="list-group-item">
                                    <a class="list-group-item" asp-page="MessageConvo" asp-route-sender="@username.Value">@username.Text</a>
                                </li>
                            }
                        }
                    </ul>

                    <div class="mt-3">
                        <button class="btn btn-primary w-100">NEW MESSAGE</button>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-7 chat-sidebar empty-message-box d-flex align-items-center justify-content-center p-3 mt-5">
                <p class="text-center">Select a conversation on the left to see messages.</p>
            </div>
        </div>
    </div>
</body>
</html>